import type { CityDriftData } from "./types";

export const cityDriftData = {
  defaults: {
    prompt: "我想吃火锅，然后去公园散步，最后顺路回家。",
  },
  quickPrompts: [
    "我想吃火锅，然后去公园散步，最后顺路回家。",
    "我想看电影，然后吃火锅，再去公园走走。",
    "我想买面包，喝杯咖啡，然后逛一下书店。",
  ],
  categoryMeta: {
    food: { label: "轻晚餐", short: "吃" },
    sichuan: { label: "川菜", short: "川" },
    cinema: { label: "电影", short: "影" },
    park: { label: "公园散步", short: "园" },
    walk: { label: "城市散步", short: "走" },
    grocery: { label: "顺路补给", short: "买" },
    cafe: { label: "咖啡小坐", short: "咖" },
    bookstore: { label: "书店停留", short: "书" },
    gallery: { label: "看展", short: "展" },
    dessert: { label: "甜品收尾", short: "甜" },
    riverside: { label: "滨水散步", short: "江" },
    market: { label: "市集补给", short: "集" },
  },
  clusters: {
    jingan: {
      label: "静安 · 苏河线",
      accent: "通勤切换少，适合工作日晚间直接出发",
    },
    xuhui: {
      label: "徐汇 · 衡山路线",
      accent: "松弛感更强，适合周末慢节奏半天",
    },
    huangpu: {
      label: "黄浦 · 滨江线",
      accent: "夜景和展览密度高，适合黄昏后出门",
    },
  },
  venues: [
    {
      id: "pepper-house",
      name: "辣风小馆",
      cluster: "jingan",
      area: "静安寺",
      address: "静安区愚园路78号",
      latitude: 31.2287,
      longitude: 121.4465,
      categories: ["sichuan", "food"],
      duration: 65,
      outdoor: false,
      rating: 4.8,
      hours: "11:00-21:30",
      crowd: "18:30 前到更稳，翻台快",
      summary: "下班后不需要绕路太远，麻辣但不燥，适合补充能量。",
      tags: ["工作日晚餐", "一个人也友好"],
      demoCanClose: true,
      ugc: {
        author: "@阿绵",
        verified: "近 14 天到访",
        title: "辣子鸡和冰粉很稳，晚高峰也不用等太久",
        stay: "建议停留 50-70 分钟",
        tip: "如果要赶下一个点，入座前先点单会更顺。",
      },
    },
    {
      id: "creek-path",
      name: "苏河慢行带",
      cluster: "jingan",
      area: "苏州河",
      address: "静安区苏州河步道西康路入口",
      latitude: 31.239,
      longitude: 121.446,
      categories: ["park", "walk", "riverside"],
      duration: 40,
      outdoor: true,
      rating: 4.7,
      hours: "全天开放",
      crowd: "饭后去最舒服",
      summary: "从商圈转入水岸，节奏立刻放慢，适合把晚餐和回家之间留一段空。",
      tags: ["步行友好", "夜景轻松"],
      ugc: {
        author: "@Kiko",
        verified: "近 7 天到访",
        title: "灯光不会太吵，饭后散 30 分钟刚好",
        stay: "建议停留 30-45 分钟",
        tip: "如果下雨就别硬走，旁边可以切换到室内书店或展览。",
      },
    },
    {
      id: "daily-harvest",
      name: "Daily Harvest 精选超市",
      cluster: "jingan",
      area: "静安嘉里中心",
      address: "静安区南京西路1515号嘉里中心B1",
      latitude: 31.2304,
      longitude: 121.4523,
      categories: ["grocery", "market"],
      duration: 20,
      outdoor: false,
      rating: 4.5,
      hours: "10:00-22:00",
      crowd: "晚 9 点前补货稳定",
      summary: "适合在回家前补生鲜、零食和次日早餐，不需要额外绕一圈。",
      tags: ["顺路采买", "回家前补给"],
      ugc: {
        author: "@Dawn",
        verified: "近 30 天到访",
        title: "小而精，买回家做早餐的东西很齐",
        stay: "建议停留 15-20 分钟",
        tip: "如果时间快不够，直接锁定即食区会最快。",
      },
    },
    {
      id: "north-window-books",
      name: "北窗书房",
      cluster: "jingan",
      area: "陕西北路",
      address: "静安区陕西北路457号2层",
      latitude: 31.2248,
      longitude: 121.444,
      categories: ["bookstore", "cafe"],
      duration: 45,
      outdoor: false,
      rating: 4.6,
      hours: "10:00-21:00",
      crowd: "工作日下午人更少",
      summary: "适合替代户外散步，保留“放慢节奏”的感觉。",
      tags: ["下雨替代", "可坐可翻书"],
      ugc: {
        author: "@Mori",
        verified: "近 10 天到访",
        title: "灯光舒服，适合在这里把整条路线缓一缓",
        stay: "建议停留 35-50 分钟",
        tip: "靠窗位适合整理照片或补看攻略。",
      },
    },
    {
      id: "frame-lab",
      name: "Frame Lab 小展厅",
      cluster: "jingan",
      area: "江宁路",
      address: "静安区江宁路366号",
      latitude: 31.2362,
      longitude: 121.4498,
      categories: ["gallery"],
      duration: 55,
      outdoor: false,
      rating: 4.7,
      hours: "11:00-20:00",
      crowd: "周末下午更热闹",
      summary: "面积不大但信息密度高，适合作为天气变化时的室内替换。",
      tags: ["室内备选", "展览快看"],
      ugc: {
        author: "@Pia",
        verified: "近 18 天到访",
        title: "一小时内能看完，不会打乱当天节奏",
        stay: "建议停留 40-60 分钟",
        tip: "先看动线图再进场，会更容易把握时间。",
      },
    },
    {
      id: "sugar-dock",
      name: "甜湾手作铺",
      cluster: "jingan",
      area: "铜仁路",
      address: "静安区铜仁路92号",
      latitude: 31.2236,
      longitude: 121.4509,
      categories: ["dessert", "cafe"],
      duration: 30,
      outdoor: false,
      rating: 4.6,
      hours: "11:00-22:00",
      crowd: "晚饭后 8 点前最稳",
      summary: "适合给下班路线一个轻量收尾，不需要大段停留。",
      tags: ["收尾轻松", "可外带"],
      ugc: {
        author: "@Lena",
        verified: "近 14 天到访",
        title: "可坐也可带走，适合在回家前吃点甜的",
        stay: "建议停留 20-30 分钟",
        tip: "想省时间可以直接外带布丁和咖啡。",
      },
    },
    {
      id: "red-bowl",
      name: "赤碗川味研究所",
      cluster: "xuhui",
      area: "衡山路",
      address: "徐汇区衡山路237号",
      latitude: 31.2077,
      longitude: 121.4446,
      categories: ["sichuan", "food"],
      duration: 70,
      outdoor: false,
      rating: 4.7,
      hours: "11:30-21:00",
      crowd: "周末午后需要等位",
      summary: "偏精致的川味表达，适合周末轻松路线而不是快速打卡。",
      tags: ["周末友好", "环境更安静"],
      demoCanClose: true,
      ugc: {
        author: "@River",
        verified: "近 20 天到访",
        title: "更适合慢慢吃，适合和书店或散步排在一起",
        stay: "建议停留 60-75 分钟",
        tip: "如果想留更多时间给展览，可以只点两道主菜。",
      },
    },
    {
      id: "music-green",
      name: "衡山绿地步道",
      cluster: "xuhui",
      area: "衡山路口袋公园",
      address: "徐汇区衡山路811号口袋绿地",
      latitude: 31.2089,
      longitude: 121.4458,
      categories: ["park", "walk"],
      duration: 35,
      outdoor: true,
      rating: 4.5,
      hours: "全天开放",
      crowd: "傍晚最舒服",
      summary: "树荫和小径很集中，短时间也有“真正出来了”的感觉。",
      tags: ["散步快进版", "适合周末上午"],
      ugc: {
        author: "@Suki",
        verified: "近 12 天到访",
        title: "不用走太多就能切换状态，适合吃完饭慢慢晃",
        stay: "建议停留 25-40 分钟",
        tip: "夏天建议把这里放到傍晚，不然会偏晒。",
      },
    },
    {
      id: "lane-fresh",
      name: "Lane Fresh 食材站",
      cluster: "xuhui",
      area: "天平路",
      address: "徐汇区天平路392号",
      latitude: 31.2117,
      longitude: 121.4387,
      categories: ["grocery", "market"],
      duration: 18,
      outdoor: false,
      rating: 4.4,
      hours: "09:30-21:30",
      crowd: "19:00 后便利熟食最全",
      summary: "路线尾声补给非常方便，适合把“买完就回家”落下来。",
      tags: ["便利补给", "尾站友好"],
      ugc: {
        author: "@Lulu",
        verified: "近 25 天到访",
        title: "晚饭后顺手拿第二天早餐，很省脑力",
        stay: "建议停留 10-20 分钟",
        tip: "别在这里久逛，直接按清单买会更高效。",
      },
    },
    {
      id: "paper-moon",
      name: "纸月书店",
      cluster: "xuhui",
      area: "永康路",
      address: "徐汇区永康路121号",
      latitude: 31.2097,
      longitude: 121.4492,
      categories: ["bookstore", "cafe"],
      duration: 50,
      outdoor: false,
      rating: 4.8,
      hours: "10:00-22:00",
      crowd: "下午 3 点后气氛最好",
      summary: "书和咖啡混合得自然，适合把路线做得更柔和。",
      tags: ["书店咖啡", "安静"],
      ugc: {
        author: "@Didi",
        verified: "近 11 天到访",
        title: "比起打卡，更适合真的坐下来待一会儿",
        stay: "建议停留 40-55 分钟",
        tip: "如果后面还有展览，别坐太久，留 50 分钟最舒服。",
      },
    },
    {
      id: "west-bund-art",
      name: "西岸小型展馆",
      cluster: "xuhui",
      area: "西岸",
      address: "徐汇区龙腾大道2555号",
      latitude: 31.1887,
      longitude: 121.454,
      categories: ["gallery"],
      duration: 65,
      outdoor: false,
      rating: 4.7,
      hours: "10:00-18:00",
      crowd: "周末下午偏满",
      summary: "很适合作为周末路线的核心站点，也能在雨天顶替户外段落。",
      tags: ["看展主站", "室内稳定"],
      ugc: {
        author: "@Noon",
        verified: "近 16 天到访",
        title: "展陈节奏舒服，一小时内不会太赶",
        stay: "建议停留 50-70 分钟",
        tip: "先看当期展简介，能更快决定是否值得停留更久。",
      },
    },
    {
      id: "riverside-toast",
      name: "滨江面包亭",
      cluster: "xuhui",
      area: "龙腾大道",
      address: "徐汇区龙腾大道2266号",
      latitude: 31.1869,
      longitude: 121.4547,
      categories: ["dessert", "riverside", "cafe"],
      duration: 30,
      outdoor: true,
      rating: 4.5,
      hours: "09:00-20:30",
      crowd: "傍晚更适合外带去江边",
      summary: "把轻甜品和滨江氛围合在一起，适合作为收尾站。",
      tags: ["甜品收尾", "适合黄昏"],
      ugc: {
        author: "@Mia",
        verified: "近 9 天到访",
        title: "可边走边吃，结束感很完整",
        stay: "建议停留 20-30 分钟",
        tip: "下雨时就不要硬去，直接切到附近书店或展馆。",
      },
    },
    {
      id: "harbor-kitchen",
      name: "泊岸厨房",
      cluster: "huangpu",
      area: "金陵东路",
      address: "黄浦区金陵东路99号",
      latitude: 31.2315,
      longitude: 121.4844,
      categories: ["food"],
      duration: 60,
      outdoor: false,
      rating: 4.5,
      hours: "11:00-21:00",
      crowd: "傍晚 6 点后上菜快",
      summary: "轻晚餐选项比较稳，适合把重心留给后面的夜景或步行。",
      tags: ["不折腾晚餐", "交通居中"],
      ugc: {
        author: "@Echo",
        verified: "近 15 天到访",
        title: "菜量刚好，不会吃得太久影响后面行程",
        stay: "建议停留 45-60 分钟",
        tip: "如果后面要去江边，点餐别太重口会更舒服。",
      },
    },
    {
      id: "fuxing-loop",
      name: "复兴口袋公园环线",
      cluster: "huangpu",
      area: "复兴中路",
      address: "黄浦区复兴中路523号口袋绿地",
      latitude: 31.2189,
      longitude: 121.4721,
      categories: ["park", "walk"],
      duration: 38,
      outdoor: true,
      rating: 4.4,
      hours: "全天开放",
      crowd: "早晨和黄昏最舒服",
      summary: "不需要完整“大公园”也能实现一次很像样的步行停留。",
      tags: ["短散步", "绿荫多"],
      ugc: {
        author: "@Poppy",
        verified: "近 13 天到访",
        title: "不是目的地式公园，但很适合塞进路线里",
        stay: "建议停留 25-40 分钟",
        tip: "如果赶时间，就只走树荫最密的那一段。",
      },
    },
    {
      id: "light-mart",
      name: "Light Mart 城市食集",
      cluster: "huangpu",
      area: "新天地",
      address: "黄浦区马当路245号B1",
      latitude: 31.218,
      longitude: 121.469,
      categories: ["grocery", "market"],
      duration: 20,
      outdoor: false,
      rating: 4.6,
      hours: "10:00-22:00",
      crowd: "夜间补给也稳定",
      summary: "更适合路线最后一站，把“买完就撤”做成默认动作。",
      tags: ["城市补货", "晚间可用"],
      ugc: {
        author: "@Anne",
        verified: "近 21 天到访",
        title: "买零食和早餐很方便，不会破坏整条路线节奏",
        stay: "建议停留 15-20 分钟",
        tip: "如果前面已经走累了，这里直接外带最省力。",
      },
    },
    {
      id: "atelier-box",
      name: "Atelier Box 展示空间",
      cluster: "huangpu",
      area: "苗江路",
      address: "黄浦区苗江路678号",
      latitude: 31.2045,
      longitude: 121.492,
      categories: ["gallery"],
      duration: 55,
      outdoor: false,
      rating: 4.6,
      hours: "10:30-19:00",
      crowd: "雨天人会更多",
      summary: "适合在天气变化时保持路线质感，不用为“本来想散步”而完全重来。",
      tags: ["雨天救场", "节奏稳定"],
      ugc: {
        author: "@Momo",
        verified: "近 8 天到访",
        title: "空间不大但很完整，适合 1 小时窗口",
        stay: "建议停留 45-55 分钟",
        tip: "如果你是黄昏出发，把这里放在第二站最顺。",
      },
    },
    {
      id: "halfday-study",
      name: "半日研究所",
      cluster: "huangpu",
      area: "思南路",
      address: "黄浦区思南路52号",
      latitude: 31.216,
      longitude: 121.4657,
      categories: ["bookstore", "cafe"],
      duration: 48,
      outdoor: false,
      rating: 4.7,
      hours: "10:00-21:30",
      crowd: "午后阅读氛围最好",
      summary: "可以是散步的替代，也可以是整个路线的精神支点。",
      tags: ["阅读停留", "咖啡共存"],
      ugc: {
        author: "@Theo",
        verified: "近 17 天到访",
        title: "更像一个愿意待着的地方，而不只是拍照点",
        stay: "建议停留 35-50 分钟",
        tip: "想要效率一点就直奔二层坐席。",
      },
    },
    {
      id: "bund-sweet",
      name: "外滩甜铺",
      cluster: "huangpu",
      area: "中山东二路",
      address: "黄浦区中山东二路469号",
      latitude: 31.2405,
      longitude: 121.4905,
      categories: ["dessert", "riverside"],
      duration: 28,
      outdoor: false,
      rating: 4.6,
      hours: "11:00-22:30",
      crowd: "晚 8 点后更适合收尾",
      summary: "把甜品和滨江结束感结合在一起，适合黄昏后路线。",
      tags: ["夜景收尾", "短停留"],
      ugc: {
        author: "@June",
        verified: "近 19 天到访",
        title: "不是为了久坐，而是给整条路线一个结束句号",
        stay: "建议停留 20-30 分钟",
        tip: "如果前面已经在江边走够了，这里就直接打包外带。",
      },
    },
  ],
  sharedRoutes: [
    {
      id: "afterwork-spice",
      title: "下班回血 4 小时",
      description: "川菜 + 饭后散步 + 回家补给，尽量不绕路。",
      promptSeed: "我从公司附近出发，有 4 小时，想吃川菜、散步、再顺路买点东西。",
      desiredCategories: ["sichuan", "park", "grocery"],
      timeHours: 4,
    },
    {
      id: "slow-saturday",
      title: "周末松弛半天",
      description: "咖啡、书店、展览串成一条安静路线。",
      promptSeed: "周六上午我有 5 小时，想喝咖啡、逛书店、再去看展。",
      desiredCategories: ["cafe", "bookstore", "gallery"],
      timeHours: 5,
    },
    {
      id: "river-evening",
      title: "黄昏滨江线",
      description: "轻晚餐 + 江边停留 + 甜品收尾，适合 3 小时轻出门。",
      promptSeed: "今晚我有 3 小时，想简单吃点东西，去江边走走，最后吃个甜品。",
      desiredCategories: ["food", "riverside", "dessert"],
      timeHours: 3,
    },
  ],
} satisfies CityDriftData;
